### ISSUE TITLE
Importing olm: "undefined symbol: olm_clear_pk_signing"

### ISSUE THREAD

**Issue by c7hm4r** [matrix-org/olm#20]
I built libolm and its python bindings from source with `make`. Running `weechat-matrix` which uses the python bindings yields the following error:

```
Traceback (most recent call last):
  File "/home/christoph/.weechat/python/matrix.py", line 34, in <module>
    from nio import RemoteProtocolError, RemoteTransportError, TransportType
  File "/home/christoph/.local/lib/python3.7/site-packages/nio/__init__.py", line 2, in <module>
    from .client import *
  File "/home/christoph/.local/lib/python3.7/site-packages/nio/client/__init__.py", line 3, in <module>
    from .base_client import Client, ClientConfig, logged_in, store_loaded
  File "/home/christoph/.local/lib/python3.7/site-packages/nio/client/base_client.py", line 23, in <module>
    from ..crypto import ENCRYPTION_ENABLED
  File "/home/christoph/.local/lib/python3.7/site-packages/nio/crypto/__init__.py", line 5, in <module>
    from .sessions import (
  File "/home/christoph/.local/lib/python3.7/site-packages/nio/crypto/sessions.py", line 23, in <module>
    import olm
  File "/home/christoph/.local/lib/python3.7/site-packages/olm/__init__.py", line 24, in <module>
    from .utility import ed25519_verify, OlmVerifyError, OlmHashError, sha256
  File "/home/christoph/.local/lib/python3.7/site-packages/olm/utility.py", line 38, in <module>
    from _libolm import ffi, lib  # type: ignore
ImportError: /home/christoph/.local/lib/python3.7/site-packages/_libolm.abi3.so: undefined symbol: olm_clear_pk_signing
```
The file `/home/christoph/.local/lib/python3.7/site-packages/_libolm.abi3.so` exists.

Fedora 30, Python 3.7

**Comment by uhoreg** [comment]
do you have libolm.so.3 installed somewhere where Python can find it?

**Comment by poljar** [comment]
The error indicates that there is a mismatch between the libolm version that was used to build the python bindings and the one that the installed python bindings are using.

Weechat is a little bit weird in that regard. It doesn't completely reload all the libraries unless it gets restarted. If that's not the case you can check if your libolm library has the required symbol with:
```shell
$ nm -D -C -g /usr/lib/libolm.so | grep clear_pk_signing
000000000000e1c0 T olm_clear_pk_signing
```
Make sure to check the libolm version that the python bindings are using:
```shell
$ ldd /usr/lib/python3.7/site-packages/_libolm.abi3.so | grep libolm
	libolm.so.3 => /usr/lib/libolm.so.3 (0x00007f682cf9c000)
```
