### ISSUE TITLE
Build olm on openbsd

### ISSUE THREAD

**Issue by caywin25** [matrix-org/olm#32]
Hello, 

I try to build olm on openbsd (6.6) but I have an issue when I run make olm-python3 : 

```
DEVELOP= python3 setup.py build
/home/user/olm/python/.eggs/cffi-1.14.0-py3.7-openbsd-6.6-amd64.egg/cffi/cparser.py:153: UserWarning: String literal found in cdef() or type source. String literals are ignored here, but you should remove them anyway because some character sequences confuse pre-parsing.
  warnings.warn("String literal found in cdef() or type source. "
Traceback (most recent call last):
  File "/home/user/olm/python/.eggs/cffi-1.14.0-py3.7-openbsd-6.6-amd64.egg/cffi/cparser.py", line 305, in _parse
    ast = _get_parser().parse(fullcsource)
  File "/home/user/olm/python/.eggs/pycparser-2.20-py3.7.egg/pycparser/c_parser.py", line 152, in parse
    debug=debuglevel)
  File "/home/user/olm/python/.eggs/pycparser-2.20-py3.7.egg/pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/user/olm/python/.eggs/pycparser-2.20-py3.7.egg/pycparser/ply/yacc.py", line 1118, in parseopt_notrack
    p.callable(pslice)
  File "/home/user/olm/python/.eggs/pycparser-2.20-py3.7.egg/pycparser/c_parser.py", line 565, in p_pp_directive
    self._token_coord(p, 1))
  File "/home/user/olm/python/.eggs/pycparser-2.20-py3.7.egg/pycparser/plyparser.py", line 67, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: <cdef source string>:3:1: Directives not supported yet

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 30, in <module>
    zip_safe=False
  File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.7/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 444, in __init__
    k: v for k, v in attrs.items()
  File "/usr/local/lib/python3.7/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 732, in finalize_options
    ep.load()(self, ep.name, value)
  File "/home/user/olm/python/.eggs/cffi-1.14.0-py3.7-openbsd-6.6-amd64.egg/cffi/setuptools_ext.py", line 217, in cffi_modules
    add_cffi_module(dist, cffi_module)
  File "/home/user/olm/python/.eggs/cffi-1.14.0-py3.7-openbsd-6.6-amd64.egg/cffi/setuptools_ext.py", line 49, in add_cffi_module
    execfile(build_file_name, mod_vars)
  File "/home/user/olm/python/.eggs/cffi-1.14.0-py3.7-openbsd-6.6-amd64.egg/cffi/setuptools_ext.py", line 25, in execfile
    exec(code, glob, glob)
  File "olm_build.py", line 53, in <module>
    ffibuilder.cdef(f.read(), override=True)
  File "/home/user/olm/python/.eggs/cffi-1.14.0-py3.7-openbsd-6.6-amd64.egg/cffi/api.py", line 112, in cdef
    self._cdef(csource, override=override, packed=packed, pack=pack)
  File "/home/user/olm/python/.eggs/cffi-1.14.0-py3.7-openbsd-6.6-amd64.egg/cffi/api.py", line 126, in _cdef
    self._parser.parse(csource, override=override, **options)
  File "/home/user/olm/python/.eggs/cffi-1.14.0-py3.7-openbsd-6.6-amd64.egg/cffi/cparser.py", line 358, in parse
    self._internal_parse(csource)
  File "/home/user/olm/python/.eggs/cffi-1.14.0-py3.7-openbsd-6.6-amd64.egg/cffi/cparser.py", line 363, in _internal_parse
    ast, macros, csource = self._parse(csource)
  File "/home/user/olm/python/.eggs/cffi-1.14.0-py3.7-openbsd-6.6-amd64.egg/cffi/cparser.py", line 307, in _parse
    self.convert_pycparser_error(e, csource)
  File "/home/user/olm/python/.eggs/cffi-1.14.0-py3.7-openbsd-6.6-amd64.egg/cffi/cparser.py", line 336, in convert_pycparser_error
    raise CDefError(msg)
cffi.CDefError: cannot parse "#ifndef OLM_H_"
<cdef source string>:3:1: Directives not supported yet
*** Error 1 in /home/user/olm/python (Makefile:24 'olm-python3')
```
Could you help me please ?
Regards

**Comment by poljar** [comment]
This seems like the include files haven't been pre-processed correctly? They are generated using the Makefile [here](https://gitlab.matrix.org/matrix-org/olm/-/blob/master/python/Makefile#L6).

**Comment by caywin25** [comment]
Thank for your reply.
I just redid the whole thing from the beginning, but now I have this mistake: 

> 
> Traceback (most recent call last):
>   File "setup.py", line 30, in <module>
>     zip_safe=False
>   File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
>     return distutils.core.setup(**attrs)
>   File "/usr/local/lib/python3.7/distutils/core.py", line 108, in setup
>     _setup_distribution = dist = klass(attrs)
>   File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 444, in __init__
>     k: v for k, v in attrs.items() 
>   File "/usr/local/lib/python3.7/distutils/dist.py", line 292, in __init__                           
>     self.finalize_options()                                                                          
>   File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 732, in finalize_options    
>     ep.load()(self, ep.name, value)                                                                  
>   File "/usr/local/lib/python3.7/site-packages/cffi/setuptools_ext.py", line 217, in cffi_modules    
>     add_cffi_module(dist, cffi_module)                                                               
>   File "/usr/local/lib/python3.7/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module  
>     execfile(build_file_name, mod_vars)                                                              
>   File "/usr/local/lib/python3.7/site-packages/cffi/setuptools_ext.py", line 25, in execfile         
>     exec(code, glob, glob)                                                                           
>   File "olm_build.py", line 55, in <module>                                                          
>     with open(os.path.join(PATH, "include/olm/pk.h")) as f:                                          
> FileNotFoundError: [Errno 2] No such file or directory: 'include/olm/pk.h'                           
> *** Error 1 in /home/user/olm/python (Makefile:24 'olm-python3') 

Here are commands I made: 
1. clone repositorie
2. cmake . -Bbuild
3. cmake --build build
4. cd python
5. make olm-python3

Thank for your help.

**Comment by caywin25** [comment]
Maybe we need to adapt the MakeFile file for OpenBSD build?

**Comment by uhoreg** [comment]
What happens of you run `make headers` in the python directory?

**Comment by caywin25** [comment]
I have this output with your command @uhoreg : 

[output.txt](https://github.com/matrix-org/olm/files/4644844/output.txt)

Thank you

**Comment by uhoreg** [comment]
Is it outputting the

```
# 1 "../include/olm/pk.h"                                           
# 1 "<built-in>" 1                                                  
# 1 "<built-in>" 3                                                  
# 349 "<built-in>" 3                                                
# 1 "<command line>" 1                                              
# 1 "<built-in>" 2
# 1 "../include/olm/pk.h" 2                                         
# 14 "../include/olm/pk.h"
...
```

lines to your terminal?

**Comment by caywin25** [comment]
Yes, when I run make olm-python3 I can see these lines.
Do you need full output ?

**Comment by uhoreg** [comment]
No, it looks like it's outputting the files to stdout instead of writing the files to the filesystem like it should.  I'll investigate.

**Comment by caywin25** [comment]
Ok thank you :)

**Comment by uhoreg** [comment]
It looks like LLVM wasn't happy about the `-o` option after the source files.  It should be fixed now in the latest `master`.
