### ISSUE TITLE
Installing python-olm via pip under FreeBSD fails

### ISSUE THREAD

**Issue by modk** [matrix-org/olm#44]
A `pip install python-olm` fails on a default FreeBSD 12.1-RELEASE installation with the following error:

```
    build/temp.freebsd-12.1-RELEASE-p7-amd64-3.7/_libolm.c:493:18: fatal error: 
'olm/olm.h' file not found                                                      
            #include <olm/olm.h>                                                
                     ^~~~~~~~~~~                                                
    1 error generated.                                                          
    error: command 'cc' failed with exit status 1                               
    ----------------------------------------                                    
ERROR: Command "/usr/local/bin/python3.7 -u -c 'import setuptools, tokenize;__fi
le__='"'"'/tmp/pip-install-uckfawlj/python-olm/setup.py'"'"';f=getattr(tokenize,
 '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"
'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /
tmp/pip-record-_t6gyim0/install-record.txt --single-version-externally-managed -
-compile --user --prefix=" failed with error code 1 in /tmp/pip-install-uckfawlj
/python-olm/
```

The problem can be fixed by adding `/usr/local/include` to the include path:
```
pip install --global-option=build_ext --global-option="-I/usr/local/include" python-olm.
```
It would be nice if this worked out of the box though :) Presumably `/usr/include` is hardcoded?

**Comment by uhoreg** [comment]
How did you install libolm?

**Comment by modk** [comment]
Via the regular package manager:
```
# pkg info -l olm                  
olm-3.1.4:
        /usr/local/include/olm/inbound_group_session.h
        /usr/local/include/olm/olm.h
[..]
```
 `/usr/local` is the default PREFIX in FreeBSD.

**Comment by uhoreg** [comment]
I don't know much about FreeBSD (or any BSDs for that matter), but I find it strange that it installs things in `/usr/local/include` by default, but doesn't add `/usr/local/include` in its default include path.  I'm hesitant to make python-olm add `/usr/local/include` to its include path, as this may not be correct for some other installations.

Separately, I'm looking into providing pre-built `whl` packages for python-olm, and it should be possible to build a package for FreeBSD.

**Comment by modk** [comment]
There is not "default include path" imho. On Linux `/usr/include` might come close because every distribution installs most of its headers there but even that is not a given. On FreeBSD there is a split between system and userland where system headers reside in `/usr/include` and userland headers in `/usr/local/include`.
`cffi` uses the system compiler (clang) which, by default, only includes `/usr/include` and therefore will not find `olm/olm.h`.
I suppose a standard way to obtain the proper path is `pkg-config` but I just realized libolm does not bundle a pkg-config file for now. `cffi` supports pkg-config though, via `ffibuilder.set_source_pkgconfig()`.

**Comment by uhoreg** [comment]
> `cffi` uses the system compiler (clang) which, by default, only includes `/usr/include` and therefore will not find `olm/olm.h`.

Yeah, I was wondering why `cc` doesn't also use `/usr/local/include` by default, if `pkg` installs things in there.  But in any event...

> I suppose a standard way to obtain the proper path is `pkg-config` but I just realized libolm does not bundle a pkg-config file for now. `cffi` supports pkg-config though, via `ffibuilder.set_source_pkgconfig()`.

Right, so I suppose the right fix for this is to provide a pkg-config file (https://github.com/matrix-org/olm/issues/19) and use it.

**Comment by heywoodlh** [comment]
Just for the record, as a workaround to get this to install on FreeBSD, I used a symlink:

```bash
# ln -s /usr/local/include/olm /usr/include/olm
```

So the full install for me looked like this:

```bash
pkg install olm
ln -s /usr/local/include/olm /usr/include/olm
pip3 install python-olm
```

**Comment by uhoreg** [comment]
The latest python-olm package should be installable on FreeBSD with cmake and a C/C++ compiler (has been tested with clang).

**Comment by geomlattice** [comment]
Could this issue be reopened?

```bash
Collecting python-olm~=3.2 (from matrix-nio[e2e]>=0.14.1->matrix-commander)
  Using cached python-olm-3.2.16.tar.gz (2.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [85 lines of output]
      CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.10 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
        to tell CMake that the project requires at least <min> but has been updated
        to work with policies introduced by <max> or earlier.
      
      
      -- The CXX compiler identification is Clang 19.1.7
      -- The C compiler identification is Clang 19.1.7
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
      -- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
      -- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
      -- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
      -- Performing Test COMPILER_HAS_DEPRECATED_ATTR
      -- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
      -- Configuring done (1.9s)
      -- Generating done (0.0s)
      -- Build files have been written to: /tmp/pip-install-3qmnw0ll/python-olm_67f378877df64236af50eb201ca566e8/libolm/build
      [  1%] Building CXX object CMakeFiles/olm.dir/src/account.cpp.o
      In file included from /tmp/pip-install-3qmnw0ll/python-olm_67f378877df64236af50eb201ca566e8/libolm/src/account.cpp:15:
      In file included from /tmp/pip-install-3qmnw0ll/python-olm_67f378877df64236af50eb201ca566e8/libolm/include/olm/account.hh:18:
      /tmp/pip-install-3qmnw0ll/python-olm_67f378877df64236af50eb201ca566e8/libolm/include/olm/list.hh:106:13: error: cannot assign to variable 'other_pos' with const-qualified type 'T *const'
        106 |             ++other_pos;
            |             ^ ~~~~~~~~~
      /tmp/pip-install-3qmnw0ll/python-olm_67f378877df64236af50eb201ca566e8/libolm/include/olm/list.hh:102:19: note: variable 'other_pos' declared const here
        102 |         T * const other_pos = other._data;
            |         ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
      1 error generated.
      gmake[2]: *** [CMakeFiles/olm.dir/build.make:79: CMakeFiles/olm.dir/src/account.cpp.o] Error 1
      gmake[1]: *** [CMakeFiles/Makefile2:151: CMakeFiles/olm.dir/all] Error 2
      gmake: *** [Makefile:136: all] Error 2
      Traceback (most recent call last):
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-0fmwzpte/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 331, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-0fmwzpte/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 301, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-0fmwzpte/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 317, in run_setup
          exec(code, locals())
        File "<string>", line 4, in <module>
        File "/tmp/pip-build-env-0fmwzpte/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 115, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-0fmwzpte/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 148, in setup
          _setup_distribution = dist = klass(attrs)
                                       ^^^^^^^^^^^^
        File "/tmp/pip-build-env-0fmwzpte/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 321, in __init__
          _Distribution.__init__(self, dist_attrs)
        File "/tmp/pip-build-env-0fmwzpte/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 309, in __init__
          self.finalize_options()
        File "/tmp/pip-build-env-0fmwzpte/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 784, in finalize_options
          ep(self)
        File "/tmp/pip-build-env-0fmwzpte/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 804, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "/tmp/pip-build-env-0fmwzpte/overlay/lib/python3.11/site-packages/cffi/setuptools_ext.py", line 229, in cffi_modules
          add_cffi_module(dist, cffi_module)
        File "/tmp/pip-build-env-0fmwzpte/overlay/lib/python3.11/site-packages/cffi/setuptools_ext.py", line 50, in add_cffi_module
          execfile(build_file_name, mod_vars)
        File "/tmp/pip-build-env-0fmwzpte/overlay/lib/python3.11/site-packages/cffi/setuptools_ext.py", line 26, in execfile
          exec(code, glob, glob)
        File "olm_build.py", line 39, in <module>
          subprocess.run(
        File "/usr/local/lib/python3.11/subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['cmake', '--build', 'build']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

For further context:

```bash
uname -a
```
FreeBSD [redacted] 15.0-RELEASE FreeBSD 15.0-RELEASE releng/15.0-redacted GENERIC amd64

I have tried both 
```bash
uv tool install matrix-commander
pip install matrix-commander
```

Both fail here on this dep with this error

**Comment by uhoreg** [comment]
libolm isn't really maintained any more.  If you can submit a patch to fix the issue, then I might be able to merge it.  But it would be better for matrix-commander to switch to using [vodozemac](https://pypi.org/project/vodozemac/) instead of python-olm.

**Comment by geomlattice** [comment]
Hm. Ok how can I patch this to use vodozemac instead then? How to get started on a high level?
