### ISSUE TITLE
Cannot install on Raspberry Pi

### ISSUE THREAD

**Issue by jannis3005** [matrix-org/olm#46]
**Describe the bug**
I'm trying to get some matrix bridges to work on my Raspberry Pi 4, however I cannot get olm to install/build correctly. When I clone the repo and build the python bindings myself, all is good. But when I try to do `pip install python-olm`, I end up with an error like this:

`arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.7m -I/home/pi/synapse/bridges/mautrix-signal/env/include/python3.7m -c build/temp.linux-armv7l-3.7/_libolm.c -o build/temp.linux-armv7l-3.7/build/temp.linux-armv7l-3.7/_libolm.o -I../include
    build/temp.linux-armv7l-3.7/_libolm.c:570:18: fatal error: olm/olm.h: Datei oder Verzeichnis nicht gefunden
             #include <olm/olm.h>`

**To Reproduce**
1. Run 'pip install python-olm' on Raspberry Pi (with libolm2 install through apt if that matters)

**Expected behavior**
It should install when installing it from pip.

**Comment by jannis3005** [comment]
Never mind im kinda stupid, cloning, then building and then running python setup.py install from the virtual-env was the way to go -.-

**Comment by 42willow** [comment]
I am getting this error, I have spent days trying to find out the problem but I can't get it to work on raspberry pi os... it works fine on WSL debian though :/

```py
Traceback (most recent call last):
  File "/home/pi/element-bot/main.py", line 4, in <module>
    import simplematrixbotlib as botlib
  File "/home/pi/element-bot/lib/python3.9/site-packages/simplematrixbotlib/__init__.py", line 1, in <module>
    from simplematrixbotlib.api import Api
  File "/home/pi/element-bot/lib/python3.9/site-packages/simplematrixbotlib/api.py", line 3, in <module>
    from nio import (AsyncClient, SyncResponse, RoomMessageText, AsyncClientConfig)
  File "/home/pi/element-bot/lib/python3.9/site-packages/nio/__init__.py", line 2, in <module>
    from .client import *
  File "/home/pi/element-bot/lib/python3.9/site-packages/nio/client/__init__.py", line 3, in <module>
    from .base_client import Client, ClientConfig
  File "/home/pi/element-bot/lib/python3.9/site-packages/nio/client/base_client.py", line 36, in <module>
    from ..crypto import ENCRYPTION_ENABLED
  File "/home/pi/element-bot/lib/python3.9/site-packages/nio/crypto/__init__.py", line 23, in <module>
    from .sessions import (
  File "/home/pi/element-bot/lib/python3.9/site-packages/nio/crypto/sessions.py", line 23, in <module>
    import olm
  File "/home/pi/element-bot/lib/python3.9/site-packages/python_olm-3.2.13-py3.9-linux-armv7l.egg/olm/__init__.py", line 24, in <module>
    from .utility import ed25519_verify, OlmVerifyError, OlmHashError, sha256
  File "/home/pi/element-bot/lib/python3.9/site-packages/python_olm-3.2.13-py3.9-linux-armv7l.egg/olm/utility.py", line 39, in <module>
    from _libolm import ffi, lib  # type: ignore
ImportError: libolm.so.3: cannot open shared object file: No such file or directory
```


edit: now I'm getting this --> https://github.com/matrix-org/olm/issues/80#issuecomment-1320821611
