### ISSUE TITLE
new emcc settings cause js builds to fail on ubuntu 18

### ISSUE THREAD

**Issue by poetaster** [matrix-org/olm#57]
**Describe the bug**
As titled, the most recent make file causes javascript build to fail on ubuntu 18.04

**To Reproduce**
1.  git clone https://gitlab.matrix.org/matrix-org/olm.git
2. cd olm/
3.  make js

**Expected behavior**
build the javscript library, olm.js

**Screenshots**

```
EMCC_CLOSURE_ARGS="--externs javascript/externs.js" emcc -Wall -Werror -O3 --closure 1 --memory-init-file 0 -s NO_FILESYSTEM=1 -s INVOKE_RUN=0 -s MODULARIZE=1 \
       -s TOTAL_STACK=65536 -s TOTAL_MEMORY=262144 \
               --pre-js javascript/olm_pre.js \
               --post-js javascript/olm_outbound_group_session.js --post-js javascript/olm_inbound_group_session.js --post-js javascript/olm_pk.js --post-js javascript/olm_sas.js --post-js javascript/olm_post.js \
               --extern-pre-js javascript/olm_prefix.js \
               --extern-post-js javascript/olm_suffix.js \
               -s "EXPORTED_FUNCTIONS=@javascript/exported_functions.json" \
               -s "EXPORTED_RUNTIME_METHODS=[ALLOC_STACK]" \
               -o javascript/olm.js build/javascript/src/base64.o build/javascript/src/pickle.o build/javascript/src/account.o build/javascript/src/message.o build/javascript/src/session.o build/javascript/src/crypto.o build/javascript/src/olm.o build/javascript/src/cipher.o build/javascript/src/pk.o build/javascript/src/ratchet.o build/javascript/src/utility.o build/javascript/src/memory.o build/javascript/src/ed25519.o build/javascript/src/megolm.o build/javascript/src/error.o build/javascript/src/pickle_encoding.o build/javascript/src/inbound_group_session.o build/javascript/src/sas.o build/javascript/src/outbound_group_session.o build/javascript/lib/crypto-algorithms/sha256.o build/javascript/lib/crypto-algorithms/aes.o build/javascript/lib/curve25519-donna/curve25519-donna.o
ERROR    root: javascript/olm_prefix.js: Input file has an unknown suffix, don't know what to do with it!
Makefile:201: recipe for target 'javascript/olm.js' failed
make: *** [javascript/olm.js] Error 1
mwa@x121e:~/src/olm$ 
```

**Desktop (please complete the following information):**
 - OS: Ubununtu 
 - Version 18.04

**Additional context**

**Comment by poetaster** [comment]
To be rid of the 'suffix error' comment out the make file JS_SUFFIX and JS_PREFIX lines. That gets us:

```
mwa@x121e:~/src/olm$ make js
EMCC_CLOSURE_ARGS="--externs javascript/externs.js" emcc -Wall -Werror -O3 --closure 1 --memory-init-file 0 -s NO_FILESYSTEM=1 -s INVOKE_RUN=0 -s MODULARIZE=1 \
       -s TOTAL_STACK=65536 -s TOTAL_MEMORY=262144 \
               --pre-js javascript/olm_pre.js \
               --post-js javascript/olm_outbound_group_session.js --post-js javascript/olm_inbound_group_session.js --post-js javascript/olm_pk.js --post-js javascript/olm_sas.js --post-js javascript/olm_post.js \
                \
                \
               -s "EXPORTED_FUNCTIONS=@javascript/exported_functions.json" \
               -s "EXPORTED_RUNTIME_METHODS=[ALLOC_STACK]" \
               -o javascript/olm.js build/javascript/src/base64.o build/javascript/src/pickle.o build/javascript/src/account.o build/javascript/src/message.o build/javascript/src/session.o build/javascript/src/crypto.o build/javascript/src/olm.o build/javascript/src/cipher.o build/javascript/src/pk.o build/javascript/src/ratchet.o build/javascript/src/utility.o build/javascript/src/memory.o build/javascript/src/ed25519.o build/javascript/src/megolm.o build/javascript/src/error.o build/javascript/src/pickle_encoding.o build/javascript/src/inbound_group_session.o build/javascript/src/sas.o build/javascript/src/outbound_group_session.o build/javascript/lib/crypto-algorithms/sha256.o build/javascript/lib/crypto-algorithms/aes.o build/javascript/lib/curve25519-donna/curve25519-donna.o
WARNING  root: Assigning a non-existent settings attribute "NO_FILESYSTEM"
WARNING  root:  - perhaps a typo in emcc's  -s X=Y  notation?
WARNING  root:  - (see src/settings.js for valid values)
WARNING  root: Assigning a non-existent settings attribute "MODULARIZE"
WARNING  root:  - perhaps a typo in emcc's  -s X=Y  notation?
WARNING  root:  - (see src/settings.js for valid values)
Traceback (most recent call last):
  File "/usr/bin/emcc", line 1274, in <module>
    exec('shared.Settings.' + key + ' = ' + value)
  File "<string>", line 1, in <module>
NameError: name 'ALLOC_STACK' is not defined
Makefile:201: recipe for target 'javascript/olm.js' failed
make: *** [javascript/olm.js] Error 1

```

**Comment by uhoreg** [comment]
Sorry, but we can't really support old versions of emscripten.  If you need to build the js library on an old version of Ubuntu, you may want to use something like Docker to get a newer version of emscripten.  If you find a solution that works for both old and new versions of emscripten, we'd be happy to accept a patch, but unfortunately, we don't have the capacity to look into it ourselves.
