### ISSUE TITLE
Doesn't run on Raspberry Pi OS

### ISSUE THREAD

**Issue by 42willow** [matrix-org/olm#81]
```py
Traceback (most recent call last):
  File "/home/pi/element-bot/main.py", line 4, in <module>
    import simplematrixbotlib as botlib
  File "/home/pi/element-bot/lib/python3.9/site-packages/simplematrixbotlib/__init__.py", line 1, in <module>
    from simplematrixbotlib.api import Api
  File "/home/pi/element-bot/lib/python3.9/site-packages/simplematrixbotlib/api.py", line 3, in <module>
    from nio import (AsyncClient, SyncResponse, RoomMessageText, AsyncClientConfig)
  File "/home/pi/element-bot/lib/python3.9/site-packages/nio/__init__.py", line 2, in <module>
    from .client import *
  File "/home/pi/element-bot/lib/python3.9/site-packages/nio/client/__init__.py", line 3, in <module>
    from .base_client import Client, ClientConfig
  File "/home/pi/element-bot/lib/python3.9/site-packages/nio/client/base_client.py", line 36, in <module>
    from ..crypto import ENCRYPTION_ENABLED
  File "/home/pi/element-bot/lib/python3.9/site-packages/nio/crypto/__init__.py", line 23, in <module>
    from .sessions import (
  File "/home/pi/element-bot/lib/python3.9/site-packages/nio/crypto/sessions.py", line 23, in <module>
    import olm
  File "/home/pi/element-bot/lib/python3.9/site-packages/python_olm-3.2.13-py3.9-linux-armv7l.egg/olm/__init__.py", line 24, in <module>
    from .utility import ed25519_verify, OlmVerifyError, OlmHashError, sha256
  File "/home/pi/element-bot/lib/python3.9/site-packages/python_olm-3.2.13-py3.9-linux-armv7l.egg/olm/utility.py", line 39, in <module>
    from _libolm import ffi, lib  # type: ignore
ImportError: libolm.so.3: cannot open shared object file: No such file or directory
```

**Comment by 42willow** [comment]
fixed, reinstalled with 64 bit os and seems to work
